### ISSUE TITLE
TypeError: window.init is not a function with CLI

### ISSUE THREAD

**Issue by nicholasmeyers** [cazala/coin-hive#23]
just installed and receive the following error when trying to run the CLI

```
Initializing...
An error occured Evaluation failed: TypeError: window.init is not a function
    at <anonymous>:1:43
    at <anonymous>:1:78
```

**Comment by cazala** [comment]
Looks like the server wasn't able to serve the page where the miner and bindings are available... This might be because the port on which the page is served by default (`3002`) was taken. You can try launching the server in a different port using the `port` property in the [constructorOptions](https://github.com/cazala/coin-hive#api):

```js
const miner = await CoinHive('<site-key>', { port: 3003 });
```

Or via environment variables, like `COINHIVE_PORT=3003 coinhive <site-key>`

**Comment by Jefreesujit** [comment]
I tried giving a different port, but the issue still persists

**Comment by ger619** [comment]
How was this issues resolved?

**Comment by mirotvorez5** [comment]
Благодарю за письмо.Иван
