### ISSUE TITLE
Trying to run on Heroku

### ISSUE THREAD

**Issue by maxdignan** [cazala/coin-hive#31]
Tried it out on Heroku, but was receiving the error that Chromium couldn't start. Any thoughts on what might fix this? Thank you!

**Comment by cazala** [comment]
Hi @maxdignan, you need to add the `puppeteer-heroku-buildpack` to you app's buildpacks in order to let puppeteer lauch, here are [the instructions].(https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-heroku)

You just need to go to your app's `Settings > Buildpacks` and add this url:

https://github.com/jontewks/puppeteer-heroku-buildpack

**Comment by maxdignan** [comment]
Really appreciate it! Thank you :)
