### ISSUE TITLE
Get around 30% cut?

### ISSUE THREAD

**Issue by jackeown** [cazala/coin-hive#43]
From what I can tell, CoinHive takes 30% of your potential profits...can you use this to bypass them?

**Comment by cazala** [comment]
You can setup your own stratum proxy with that package ☝️ and mine on a pool like nanopool.org or minexmr.com which have like a 1% commision. I built a toy service [minero.pw](https://minero.pw) that works with coinhive's miner but takes only a 2% commision, and you can get payed in a different currency than Monero. You could use that or even [build your own](https://github.com/cazala/minero).

**Comment by jackeown** [comment]
So you're saying with this you don't have to pay coinhive, but you can still use their code to mine?

**Comment by sunk818** [comment]
CoinHive takes a 30% cut. Last count, that required 3.8 giga hashes (3.8 billion) to get paid 0.5 XMR. I don't know if you realize, but I can get about 1.7 megahash per day assuming 20 h/s. Will take you 2,235 days to get 0.5 XMR. 100 h/s per day is still going to take you 447 days. If you mine with a different pool, you should fine one that has a low difficulty and pays out in much smaller increments. 0.5 XMR on another pool is still going to take you an extremely long if you plan to mine via javascript. I've been doing coinhive since they came out, but I've only been able to 182 mega hashes done. :(

**Comment by cazala** [comment]
Why are you assuming 20h/s? The idea is to put the miner on you website so you get a few (maybe not 20h/s, but 5-7h/s) hashes from each visitor. If you have millions of visitors a month you will easily be in the dozens or hundreds Kh/s

Sent from my iPhone

On Oct 14, 2017, at 2:13 PM, sunk818 <notifications@github.com<mailto:notifications@github.com>> wrote:


CoinHive takes a 30% cut. Last count, that required 3.8 giga hashes (3.8 billion) to get paid 0.5 XMR. I don't know if you realize, but I can get about 1.7 megahash per day assuming 20 h/s. Will take you 2,235 days to get 0.5 XMR. 100 h/s per day is still going to take you 447 days. If you mine with a different pool, you should fine one that has a low difficulty and pays out in much smaller increments. 0.5 XMR on another pool is still going to take you an extremely long if you plan to mine via javascript. I've been doing coinhive since they came out, but I've only been able to 182 mega hashes done. :(

**Comment by cazala** [comment]
Well, yes, technically their miner can be configured by design to point to a different proxy thru the `CoinHive.CONFIG.LIB_URL` and `ConHive.CONFIG.WEBSOCKET_SHARDS` properties.. so it is just a matter setting up a proxy, and their miner can be used as it is... no need to mod it or anything.

**Comment by knoxcard** [comment]
Excelllennnnt Smithers....

**Comment by cazala** [comment]
If you are interested in mining on a different pool, I just created a tool to deploy a stratum proxy to now.sh: [CoinHive Proxy](https://coinhive-proxy.party/)

**Comment by ileathan** [comment]
Hey thanks for the cool tool @cazala I have it all working perfectly, I just have one question. Is there a way to move the CoinHive Proxy blob file onto our local machine? It says its against the ToS and Im scared they will shut it down. For example I copied "https://party-urxkllpjuy.now.sh/client" to a local machine and sourced it like normal, but it doesnt work unless i source it remotely.

**Comment by andreyputivtsev** [comment]
Theoretically, I don't see profit of using other miners than coin hive, because of "difficulty". For example, supportxmr.com (d=1000) will recieve 4x times less hashes than CoinHive (d=256). Correct me if I'm wrong

**Comment by cazala** [comment]
Yes and supportxmr.com will also give you 4x money for your shares. Difficulty doesn't impact on profits, only how often jobs will be submitted.

**Comment by ileathan** [comment]
```
    var shards = leatMine.CONFIG.WEBSOCKET_SHARDS;
    var shardIdx = this._hashString(this._siteKey) % shards.length;
```

Am I correct in assuming, running multiple instances of https://github.com/cazala/coin-hive-stratum can in turn populate `WEBSOCKET_SHARDS` and the servers will share the load?
