### ISSUE TITLE
Cannot stop within Docker

### ISSUE THREAD

**Issue by SoftCreatR** [cazala/coin-hive#59]
Installing and running within a Docker machine works fine now (thanks again). However, when running the instance with `docker run XXX`, you will see the coin-hive CLI as expected, but `q/Ctrl-C` is being ignored, so you have to forcefully shut it down via kill.

**Comment by cazala** [comment]
Yea that's because you are pressing `q` on your terminal's standard input, not in the conatiner's one. If you want to attach your terminal's standard input to the running container in order to interact with it, you can use [docker attach](https://docs.docker.com/edge/engine/reference/commandline/attach/#parent-command)

**Comment by SoftCreatR** [comment]
I am just able to use the key combination CTRL+C to get out of the process, but not to use `+`, `-`, `q` or `a` to control the running process.
