### ISSUE TITLE
How to add etn miner in site 

### ISSUE THREAD

**Issue by rimanve** [cazala/coin-hive#77]
Hi, thanks for the project.

i want to add a ETN miner in my site.

i don't know much about coding and javascript, i think i read the guide maybe 10 times and still didn't figure it out how to get it work.
will it work if i upload the entire code to site and then add this to html codes:

`<script src="/src/miner.js"></script>

<script>
const miner = await CoinHive('<MY-ELECTRONEUM-ADDRESS>', {
  pool: {
    host: 'etnpool.minekitten.io',
    port: 3333
  }
});
miner.start();
</script>
`

**Comment by cazala** [comment]
Hi, this package is not for mining on the browser, but for mining on node.js

If you want to mine ETN on the web, you can, what you need is a proxy, then you point your web miners to your proxy, and the proxy to the ETN pool.

Check [coin-hive-stratum](https://github.com/cazala/coin-hive-stratum). You will need a server capable of running node.js in order to deploy the proxy. There are guides to deploy the server to `now.sh` and DigitalOcean for free.
